server:
  port: 8090

spring:
  h2: 
   console: 
    enabled: true
    path: /h2
    settings:
      web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: true
    show_sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    # properties:
    #   hibernate.cache.use_query_cache: true
    #   hibernate.generate_statistics: true 

app:
  message: Welcome to the example (DEV) of spring-boot (Gradle/Java) RESTful API application with controllers/services/repository using 